// Approve a still take and put it on the site.
//
//   node scripts/approve-still.mjs <shot-id> <take>     e.g. campaign-swim 2
//
// Crops and resizes stills-src/takes/<id>-t<N>.png to the shot's size and writes public/<out> as JPEG
// (the previous image is backed up once to stills-src/images-orig/). For an on-model product shot it
// also registers the slug in src/data/on-model.ts and, for the first colourway of a design, keeps the
// model as stills-src/models/<family>.png so the other colourways show the same person.

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { SHOTS } from "./stills-shots.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const [, , id, take] = process.argv;
const shot = SHOTS[id];
const src = join(root, "stills-src", "takes", `${id}-t${take}.png`);
if (!shot || !existsSync(src)) {
  console.error(`Usage: node scripts/approve-still.mjs <shot-id> <take>  (no ${src})`);
  process.exit(1);
}

const dest = join(root, "public", shot.out);
const backup = join(root, "stills-src", "images-orig", shot.out);
if (existsSync(dest) && !existsSync(backup)) {
  mkdirSync(dirname(backup), { recursive: true });
  copyFileSync(dest, backup);
}
const [w, h] = shot.size;
await sharp(src).resize(w, h, { fit: "cover", position: "attention" }).jpeg({ quality: 86, mozjpeg: true }).toFile(dest);

const approvedDir = join(root, "stills-src", "approved");
mkdirSync(approvedDir, { recursive: true });
copyFileSync(src, join(approvedDir, `${id}.png`));

if (shot.family) {
  const models = join(root, "stills-src", "models");
  mkdirSync(models, { recursive: true });
  const ref = join(models, `${shot.family}.png`);
  if (!existsSync(ref)) copyFileSync(src, ref);

  const file = join(root, "src", "data", "on-model.ts");
  const slugs = new Set(existsSync(file) ? [...readFileSync(file, "utf8").matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1]) : []);
  slugs.add(id);
  writeFileSync(
    file,
    `// Generated by scripts/approve-still.mjs: products with an approved on-model shot (public/products/<slug>-model.jpg).\nexport const onModel = new Set<string>([\n${[...slugs].sort().map((s) => `  "${s}",`).join("\n")}\n]);\n`,
  );
}
console.log(`${id}: take ${take} → public/${shot.out} (${w}×${h})`);
